services:
    debach_typography.php_typography:
        class: Debach\PhpTypography\PhpTypography
        public: true
        calls:
            - [set_smart_diacritics, [false]]
            - [set_style_initial_quotes, [false]]
            - [set_hyphenation_language, ["%locale%"]]
            - [set_smart_quotes_language, ["%locale%"]]

    debach_typography.transformer:
        class: Debach\TypographyBundle\Form\DataTransformer\TypographyTransformer
        arguments:
            - "@service_container"

    Debach\TypographyBundle\Form\DataTransformer\TypographyTransformer:
        alias: debach_typography.transformer

    debach_typography.extension:
        class:     Debach\TypographyBundle\Extension\Extension
        arguments: ["@debach_typography.transformer"]
        tags:
          - { name: twig.extension }
